### ISSUE TITLE
sirius conda package on conda-forge?

### ISSUE THREAD

**Issue by ltalirz** [electronic-structure/SIRIUS#621]
Hi guys, I was wondering whether there is interest in creating a conda package for sirius.

While a conda sirius won't get you optimal performance for your machine, the pre-built binaries make it much easier and faster for new prospective users to give it a try.

Most of the core Sirius dependencies already are on conda-forge; I guess one would just need to add spfft and spla.
There is even a way to build gpu-enabled packages, but I have no experience with this so far.

I'm happy to help with this but I'm sure I'll also need some advice from the maintainers on how to best build the libraries.

P.S. [QE](https://github.com/conda-forge/qe-feedstock), [cp2k](https://anaconda.org/conda-forge/cp2k), [lammps](https://anaconda.org/conda-forge/lammps), [abinit](https://anaconda.org/conda-forge/abinit), [siesta](https://anaconda.org/conda-forge/siesta), etc. are already on conda-forge.

**Comment by toxa81** [comment]
@AdhocMan Simon, if it starts from spla and spfft, can I ask you to have a look?

**Comment by AdhocMan** [comment]
I don't have any experience writing conda packages, but I'd certainly be happy to help.
This is a first attempt for SpFFT, which seems to be working, and may be useful as a starting point:
```
{% set name = "spfft" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eth-cscs/SpFFT/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 541f6d92993655b68404cfea60d84ce0a7644eed49dff7e7437db818127700f9

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - cmake >=3.11.0
  host:
    - {{ mpi }}
    - fftw
  run:
    - {{ mpi }}

test:
  commands:
    - test -f "${PREFIX}/lib64/libspfft${SHLIB_EXT}" || test -f "${PREFIX}/lib/libspfft${SHLIB_EXT}"

about:
  home: https://github.com/eth-cscs/SpFFT.git
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sparse 3D FFT library
  doc_url: https://spfft.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/eth-cscs/SpFFT
```
And build.sh:
```
mkdir -p build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX="${PREFIX}"  -DSPFFT_MPI=ON -DSPFFT_OMP=ON -DSPFFT_GPU_BACKEND=OFF -DSPFFT_GPU_DIRECT=OFF -DSPFFT_SINGLE_PRECISION=ON -DSPFFT_STATIC=OFF -DSPFFT_FORTRAN=ON -DSPFFT_BUILD_TESTS=OFF
make -j2 install
```
